# Generated by Django 4.0 on 2022-02-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('fax', models.IntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=3)),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('retirement_date', models.DateField()),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_job_name', models.CharField(max_length=20)),
                ('first_job_post', models.CharField(max_length=10)),
                ('first_job_duration', models.CharField(max_length=8)),
                ('second_job_name', models.CharField(max_length=20)),
                ('second_job_post', models.CharField(max_length=10)),
                ('second_job_duration', models.CharField(max_length=8)),
                ('third_job_name', models.CharField(max_length=20)),
                ('third_job_post', models.CharField(max_length=10)),
                ('third_job_duration', models.CharField(max_length=8)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEducaionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honours', models.CharField(choices=[('BSC', 'BSC'), ('BBA', 'BBA'), ('Honours', 'Honours')], max_length=7)),
                ('masters', models.CharField(choices=[('MBA', 'MBA'), ('MSC', 'MSC')], max_length=3)),
                ('phd', models.CharField(choices=[('PhD', 'PhD')], max_length=3)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
        ),
    ]
