# Generated by Django 4.0 on 2022-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='first_job_post',
            new_name='first_job_designation',
        ),
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='second_job_post',
            new_name='second_job_designation',
        ),
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='third_job_post',
            new_name='third_job_designation',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
