# Generated by Django 4.0 on 2022-02-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_first_job_post_teacherexperience_first_job_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Teacher_Educaional_Qualification', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherexperience',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Teacher_Experience', to='teacher.teacher'),
        ),
    ]
