# Generated by Django 4.0 on 2022-02-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='surname',
            new_name='last_name',
        ),
    ]
