# Generated by Django 4.0.1 on 2022-02-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_rename_surname_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Cristian', 'Cristian'), ('Buddist', 'Buddist')], default='Muslim', max_length=8),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', '0+'), ('O-', '0-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mother_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='honours',
            field=models.CharField(choices=[('BSC', 'BSC'), ('BBA', 'BBA'), ('Honours', 'Honours')], default='N\\A', max_length=7),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='masters',
            field=models.CharField(choices=[('MBA', 'MBA'), ('MSC', 'MSC')], default='N\\A', max_length=3),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='phd',
            field=models.CharField(choices=[('PhD', 'PhD')], default='=N\\A', max_length=3),
        ),
    ]
