# Generated by Django 4.0 on 2022-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_teacher_religion_alter_teacher_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='first_job_designation',
            new_name='job_designation',
        ),
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='first_job_duration',
            new_name='job_duration',
        ),
        migrations.RenameField(
            model_name='teacherexperience',
            old_name='first_job_name',
            new_name='job_name',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='second_job_designation',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='second_job_duration',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='second_job_name',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='third_job_designation',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='third_job_duration',
        ),
        migrations.RemoveField(
            model_name='teacherexperience',
            name='third_job_name',
        ),
    ]
