# Generated by Django 4.0 on 2022-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_rename_first_job_designation_teacherexperience_job_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='honours',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='masters',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='teachereducaionalqualification',
            name='phd',
            field=models.CharField(max_length=3),
        ),
    ]
