# Generated by Django 4.0.1 on 2022-02-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacherexperience_teachereducaionalqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherexperience',
            name='job_name',
        ),
        migrations.AlterField(
            model_name='teacherexperience',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
    ]
