# Generated by Django 4.0.1 on 2022-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_guardian_phone_active_student_phone_active_and_more'),
        ('teacher', '0016_rename_company_name_teacherexperience_institute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='student.Student'),
        ),
        migrations.AlterField(
            model_name='teacherexperience',
            name='job_designation',
            field=models.CharField(max_length=20),
        ),
    ]
