# Generated by Django 4.0.1 on 2022-02-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_teacher_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
    ]
