# Generated by Django 4.0.1 on 2022-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_classinformation_created_at_student_created_at_and_more'),
        ('teacher', '0018_remove_teacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='student.Student'),
        ),
    ]
