# Generated by Django 4.0.1 on 2022-02-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_teacher_archived_at_teacher_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/profile_picture'),
        ),
    ]
