# Generated by Django 4.0.1 on 2022-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_alter_teacher_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
