# Generated by Django 4.0.1 on 2022-02-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_alter_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
