# Generated by Django 4.0.1 on 2022-02-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='background_image',
            field=models.ImageField(upload_to='facilities/background_image'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
