# Generated by Django 4.0 on 2022-02-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_blood_group_classinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
