# Generated by Django 4.0.1 on 2022-02-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_guardian_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='2017-18', max_length=7),
        ),
    ]
