# Generated by Django 4.0 on 2022-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_phone_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(choices=[('2010-11', '2010-11'), ('2011-12', '2011-12'), ('2012-13', '2012-13'), ('2013-14', '2013-14'), ('2014-15', '2014-15'), ('2015-16', '2015-16'), ('2016-17', '2016-17'), ('2017-18', '2017-18'), ('2018-19', '2018-19'), ('2019-20', '2019-20'), ('2020-21', '2020-21')], default='SESSION_CHOICES_DEFAULT', max_length=7),
        ),
    ]
