# Generated by Django 4.0.1 on 2022-02-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_guardian_phone_active_student_phone_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='classinformation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Class_Information', to='student.student'),
        ),
    ]
