# Generated by Django 4.0.1 on 2022-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
