# Generated by Django 4.0.1 on 2022-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classinformation',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
