# Generated by Django 4.0.1 on 2022-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_student_otp_remove_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
